### ISSUE TITLE
Building OpenBSD 6.9 error: use of undeclared identifier 'getcontext'

### ISSUE THREAD

**Issue by murilobsd** [capnproto/capnproto#1208]
```
# os
OpenBSD 6.9 amd64
# clang version
OpenBSD clang version 10.0.1
Target: amd64-unknown-openbsd6.9
Thread model: posix
InstalledDir: /usr/bin
```

Process:

```
git clone https://github.com/sandstorm-io/capnproto.git
cd capnproto/c++
export AUTOCONF_VERSION=2.71
export AUTOMAKE_VERSION=1.16
export LIBTOOL=/usr/local/lib/libtool
autoreconf -i
./configure CC=clang CXX=clang++
make -j6 check
```
[configure.log](https://envs.sh/cp.log)

Out:

```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -pthread -O2 -DNDEBUG -pthread -DKJ_HAS_ZLIB -DKJ_HAS_OPENSSL -MT src/capnp/rpc.capnp.lo -MD -MP -MF src/capnp/.deps/rpc.capnp.Tpo -c src/capnp/rpc.capnp.c++  -fPIC -DPIC -o src/capnp/.libs/rpc.capnp.o
src/kj/async.c++:56:10: fatal error: 'ucontext.h' file not found
#include <ucontext.h>
         ^~~~~~~~~~~~
1 error generated.
*** Error 1 in target 'src/kj/async.lo'
src/kj/async-io-unix.c++:1446:20: error: variable has incomplete type 'struct ucred'
      struct ucred creds;
                   ^
src/kj/async-io-unix.c++:1446:14: note: forward declaration of 'ucred'
      struct ucred creds;
             ^
```

OpenBSD doesn't have <ucontext.h>. ucontext_t lives in <signal.h>, so i change:

[aex/kj/async.c++](https://github.com/capnproto/capnproto/blob/6b5bcc2c6e954bc6e167ac581eb628e5a462a469/c%2B%2B/src/kj/async.c%2B%2B#L56)
```c
#if __OpenBSD__
#include <signal.h>
#else
#include <ucontext.h>
#endif
```
and now the problem is this! Can someone guide me about this error?

```
src/kj/async.c++:1354:16: error: use of undeclared identifier 'getcontext'; did you mean
      'sigcontext'?
    KJ_SYSCALL(getcontext(context));
               ^
/usr/include/machine/signal.h:54:8: note: 'sigcontext' declared here
struct sigcontext {
       ^
src/kj/async.c++:1355:14: error: no member named 'uc_stack' in 'sigcontext'
    context->uc_stack.ss_size = allocSize - sizeof(Impl);
    ~~~~~~~  ^
src/kj/async.c++:1356:14: error: no member named 'uc_stack' in 'sigcontext'
    context->uc_stack.ss_sp = reinterpret_cast<char*>(stack);
    ~~~~~~~  ^
src/kj/async.c++:1357:14: error: no member named 'uc_stack' in 'sigcontext'
    context->uc_stack.ss_flags = 0;
    ~~~~~~~  ^
src/kj/async.c++:1362:14: error: no member named 'uc_link' in 'sigcontext'
    context->uc_link = 0;
    ~~~~~~~  ^
src/kj/async.c++:1454:3: error: use of undeclared identifier 'makecontext'
  makecontext(&context, reinterpret_cast<void(*)()>(&StartRoutine::run), 2, arg1, arg2);
  ^
src/kj/async.c++:1457:5: error: use of undeclared identifier 'setcontext'; did you mean
      'sigcontext'?
    setcontext(&context);
    ^
/usr/include/machine/signal.h:54:8: note: 'sigcontext' declared here
struct sigcontext {
       ^
src/kj/async-io-unix.c++:1446:20: error: variable has incomplete type 'struct ucred'
      struct ucred creds;
                   ^
src/kj/async-io-unix.c++:1446:14: note: forward declaration of 'ucred'
      struct ucred creds;
             ^
In file included from src/kj/async.c++:43:
src/kj/debug.h:543:17: error: invalid operands to binary expression ('void' and 'int')
  while (call() < 0) {
```

**Comment by kentonv** [comment]
Does OpenBSD have getcontext()/setcontext()? It looks like it might not. These functions were deprecated from POSIX, which is unfortunate since they are extremely useful.

You may need to skip support for fibers on OpenBSD. In async.c++ there are some existing #ifdef's that disable fibers when `__BIONIC__` is defined. OpenBSD will probably have to do the same. Maybe we should fold this into one macro near the top:

```
#ifndef KJ_USE_FIBERS
#if __BONIC__ || __OpenBSD__
// These platforms don't support fibers.
#define KJ_USE_FIBERS 0
#else
#define KJ_USE_FIBERS 1
#endif
#endif
```

This also allows someone to manually add `-DKJ_USE_FIBERS=0` to `CXXFLAGS` to avoid building fibers, which has come up before as a useful flag to have (see #1167). (Speaking of which, the person who reported that issue ended up using `libucontext`. Does `libucontext` work on OpenBSD? If you wanted to get fiber support, then you might want to use that.)

**Comment by SenorAgosto** [comment]
> Does libucontext work on OpenBSD? 

No, it does not compile on OpenBSD 6.9.  

It also tries to `#include <ucontext.h>` and if you change that to `#include <signal.h>` it bombs with the same errors as above with undefined context members.

**Comment by SenorAgosto** [comment]
@kentonv 

    #ifndef KJ_USE_FIBERS
    #if __BONIC__ || __OpenBSD__
    // These platforms don't support fibers.
    #define KJ_USE_FIBERS 0
    #else
    #define KJ_USE_FIBERS 1
    #endif
    #endif

I don't see the above snippet in async.c++.

    git clone https://github.com/capnproto/capnproto
    git grep USE_FIBERS
    git grep BONIC
    
I searched v0.8.0 back to v0.5.1 and I don't see `KJ_USE_FIBERS` or `__BONIC__` defined anywhere. What branch are you on? Maybe I'm missing something?

**Comment by kentonv** [comment]
@SenorAgosto I was suggesting we add that code. Also, I typo'd -- `__BONIC__` should have been `__BIONIC__`

**Comment by SenorAgosto** [comment]
@kentonv ah, okay, I see a bunch of `__BIONIC__` defs :+1:. 

I misread your comment, I didn't realize you were suggesting introducing the KJ_USE_FIBERS macro.

**Comment by ZhanYF** [comment]
Hi, thanks for keeping this thread alive!
By toggling the __BIONIC__ defs, I'm able to build & run capnproto on the latest snapshot version OpenBSD 6.9. I've been using it from some time now and it works as expected. 

I agree that KJ_USE_FIBERS is a good idea,  let's do it?

**Comment by JonasVautherin** [comment]
Just happened to end up on this issue, which was apparently resolved in #1313 and #1321.

I guess it can be closed now?

**Comment by ZhanYF** [comment]
@JonasVautherin 

Yes, the issue described here no longer exist. Please feel free to close this.

(I haven't give up porting capnproto to OpenBSD, I just don't have enough time to dig into it at the moment.)
