### ISSUE TITLE
Failing to build on musl libc due to missing getcontext/setcontext

### ISSUE THREAD

**Issue by roshii** [capnproto/capnproto#1167]
I'm trying to build on Alpine Linux v3.13 from release tarball v0.8.0 but  failing due to missing commands listed here after.
From what i [understand](https://github.com/9fans/plan9port/issues/36) [`libucontext`](https://github.com/kaniini/libucontext) seem to implement these missing commands but i fail to make anything out of it.

```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libkj-async.so: undefined reference to `swapcontext'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libkj-async.so: undefined reference to `getcontext'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libkj-async.so: undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1838: capnp-afl-testcase] Error 1
```

**Comment by kentonv** [comment]
Interesting, I guess musl doesn't implement these, maybe because POSIX considers them deprecated. But POSIX offers no replacement and this is the only portable way to implement fibers.

Some ways we could address this:
* Stopgap: You could maybe install `libucontext` and then do `./configure LIBS='-lucontext'` to force Cap'n Proto to link against it.
* We could extend the source code in `kj/async.c++` to detect musl via `#ifdef`, similar to how it detects Bionic, and disable fibers in this case.
* We could add a new build flag to disable fibers, so that the next person who discovers their libc implementation doesn't support these functions, they can disable fibers and move on.
* We could actually adopt libucontext into KJ so that we don't depend on it being provided by the system at all. This would give us more portability and protect us against future libc versions dropping support for these. We might even be able to optimize them a bit for our specific use case. But this option is probably a fair amount of work.

Happy to accept PRs.

**Comment by roshii** [comment]
Running `./configure LIBS='-lucontext'` turned out to be successful, many thanks :)

imho, a build flag would be the most appropriate as it would give musl users a choice to user fibers or not. i have little experience in c++ but i like challenges and i may try to implement this flag within the year.

p.s. i'm not closing the issue as i'm not sure how you want to keep track of things. feel free to do so however.

**Comment by kentonv** [comment]
Another solution could be to add a `configure` check that actually tries to link a program against these symbols to see if it works, and then enables fibers based on that. Autoconf is all about that sort of thing.

**Comment by Dr-Emann** [comment]
Can also be useful to disable/use libucontext in the case that [glibc's implementation is broken](https://groups.google.com/g/capnproto/c/XrEnf6XGqFA). I've patched out the fiber support at work so we don't accidently rely on fibers (and so that the capnp tests pass).

**Comment by JonasVautherin** [comment]
Quick word for those who have been using capnproto with musl before: #1409 brings support both in CMake and automake, and also [fixes a bug](https://github.com/capnproto/capnproto/pull/1409/commits/0eda701d210107e7acf4e6af13222ec185e593d7) due to glibc not using the POSIX defaults for `getaddrinfo` (using "localhost" instead of "127.0.0.1" would fail using musl).

### CMake

It adds a [WITH_FIBERS](https://github.com/capnproto/capnproto/pull/1409/files#diff-dcf6a3634b0f33c91f0508060a848c4b01305981b51a4e369a7c334137bccd40R67) option, that can be used like so:

* `-DWITH_FIBERS=ON` to compile with fibers. The configure step will fail with an error message if `getcontext`/`setcontext` are not present. You may need to install `libucontext` for this to work.
* `-DWITH_FIBERS=OFF` to compile without fibers.
* `-DWITH_FIBERS=AUTO` (default) to detect if `getcontext`/`setcontext` are present (also trying to link `libucontext` if necessary) and disabling fibers if the symbols cannot be found at all.

### Automake

It adds a [fibers](https://github.com/capnproto/capnproto/pull/1409/files#diff-a0586b852a6736f6c99f0ec541f28ed65c920b69869c3d5ea893490ee5f49795R36) argument (similar to CMake above), that can be used like so:

* `--with-fibers` to compile with fibers. The configure step will fail with an error message if `getcontext`/`setcontext` are not present. You may need to install `libucontext` for this to work.
* `--without-fibers` to compile without fibers.
* defaults to "check" to detect if `getcontext`/`setcontext` are present (also trying to link `libucontext` if necessary) and disabling fibers if the symbols cannot be found at all.

I hope this helps!

Many thanks to @kentonv and @Sarcasm for the help implementing this!
