### ISSUE TITLE
capnp 0.9.0 failed to compile on Majove

### ISSUE THREAD

**Issue by chenrui333** [capnproto/capnproto#1305]
👋  just found the latest release 0.9.0 does not compile on Mojave (macOS 10.14), error log is below:
<details>
<summary>build error</summary>

```
In file included from /tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/mutex.h:28:
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:59:64: error: use of undeclared identifier '__builtin_FILE'
  constexpr SourceLocation(Badge = Badge{}, const char* file = __builtin_FILE(),
                                                               ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:60:26: error: use of undeclared identifier '__builtin_FUNCTION'
      const char* func = __builtin_FUNCTION(), uint line = __builtin_LINE(),
                         ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:60:60: error: use of undeclared identifier '__builtin_LINE'
      const char* func = __builtin_FUNCTION(), uint line = __builtin_LINE(),
                                                           ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:61:21: error: use of undeclared identifier '__builtin_COLUMN'
      uint column = KJ_CALLER_COLUMN())
                    ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:27:28: note: expanded from macro 'KJ_CALLER_COLUMN'
#define KJ_CALLER_COLUMN() __builtin_COLUMN()
                           ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:59:13: error: constexpr constructor must initialize all members
  constexpr SourceLocation(Badge = Badge{}, const char* file = __builtin_FILE(),
            ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:77:15: note: member not initialized by constructor
  const char* fileName;
              ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:78:15: note: member not initialized by constructor
  const char* function;
              ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:79:8: note: member not initialized by constructor
  uint lineNumber;
       ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:80:8: note: member not initialized by constructor
  uint columnNumber;
       ^
5 errors generated.
In file included from /tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.c++:22:
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:59:64: error: use of undeclared identifier '__builtin_FILE'
  constexpr SourceLocation(Badge = Badge{}, const char* file = __builtin_FILE(),
                                                               ^
make[2]: *** [src/kj/CMakeFiles/kj.dir/mutex.c++.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:60:26: error: use of undeclared identifier '__builtin_FUNCTION'
      const char* func = __builtin_FUNCTION(), uint line = __builtin_LINE(),
                         ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:60:60: error: use of undeclared identifier '__builtin_LINE'
      const char* func = __builtin_FUNCTION(), uint line = __builtin_LINE(),
                                                           ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:61:21: error: use of undeclared identifier '__builtin_COLUMN'
      uint column = KJ_CALLER_COLUMN())
                    ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:27:28: note: expanded from macro 'KJ_CALLER_COLUMN'
#define KJ_CALLER_COLUMN() __builtin_COLUMN()
                           ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:59:13: error: constexpr constructor must initialize all members
  constexpr SourceLocation(Badge = Badge{}, const char* file = __builtin_FILE(),
            ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:77:15: note: member not initialized by constructor
  const char* fileName;
              ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:78:15: note: member not initialized by constructor
  const char* function;
              ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:79:8: note: member not initialized by constructor
  uint lineNumber;
       ^
/tmp/capnp-20210815-80151-159a7vv/capnproto-c++-0.9.0/src/kj/source-location.h:80:8: note: member not initialized by constructor
  uint columnNumber;
       ^
5 errors generated.
make[2]: *** [src/kj/CMakeFiles/kj.dir/source-location.c++.o] Error 1
```

</details>

The cmake command 
```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/capnp/0.9.0 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
```

relates to https://github.com/Homebrew/homebrew-core/pull/83289

**Comment by kentonv** [comment]
Hi @chenrui333,

Cap'n Proto does build on Mac, it's one of our CI targets and we haven't seen this issue. So there must be something different about your setup.

What compiler is your build using?

Could you perhaps fix the `#ifdef`s at the top of `c++/src/kj/source-location.h` so that they correctly handle your compiler? If you submit a PR that works for you, I can make a 0.9.1 release with it.

**Comment by chenrui333** [comment]
we are using
```
Clang: 11.0.0 build 1100
Xcode: 11.3.1
```

**Comment by kentonv** [comment]
Clang 11 supports `__builtin_FILE()`, and our CI has tested Clang on MacOS, so something else seems wrong here. Are you sure Homebrew isn't using a different compiler?

**Comment by kentonv** [comment]
@vlovich I don't suppose you can help figure out what's going on here? I don't have a mac.

**Comment by sfjohnson** [comment]
Hi,

Looks like the CI target is macOS 10.15 which has clang 12. For me it works on clang 12 but not clang 11. I was able to fix it by installing clang 12 on macOS 10.14 with Homebrew.

**Comment by judaew** [comment]
CI also targets macOS 10.14 with clang 11. In general, MacPorts tries to build projects for earlier versions of macOS if possible.

https://capnproto.org/install.html

This page states that the minimum version of Clang is 5.0.

**Comment by judaew** [comment]
Using a newer compiler than the version of clang included in Xcode may be a viable workaround (> clang 12), and if using a newer compiler is required, I think that's fine, but in the requirements of the capnproto states, the minimum version of Clang is 5.0. So I guess it might be a bug in the code. But if a newer compiler is required, it should be documented.

**Comment by kentonv** [comment]
Oh geez, this is Apple lying about the Clang version again.

https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_13.x_.28since_SwiftUI_framework.29_2

The version of Clang/LLVM you are using is, in fact, 8, not 11.

Apple's build of Clang defines `__clang_major__` to report the XCode version instead of the LLVM version. This has been a persistent source of pain. I don't understand why Apple does this crap.

The necessary compiler built-ins were added in Clang 9: https://releases.llvm.org/9.0.0/tools/clang/docs/LanguageExtensions.html

And we correctly detect Clang 9 here:

https://github.com/capnproto/capnproto/blob/2e086ce7df2edb69a01ecc37e5e26271acef3873/c++/src/kj/source-location.h#L37-L39

But Apple lies and makes their Clang 8 report itself as Clang 11.

If someone would like to submit a PR that adds the appropriate `#if __APPLE__` work-around I'll be happy to accept it and do a point release.

**Comment by vlovich** [comment]
Switched to using `__has_builtin` instead of checking clang version.

**Comment by judaew** [comment]
Thanks so much!

@kentonv Can you make a point release? If not, then otherwise I can apply this fix as a patch.

**Comment by kentonv** [comment]
@judaew Yeah I'll try to do it within the next week.

**Comment by judaew** [comment]
Thanks!

**Comment by kentonv** [comment]
Release candidate here:

https://capnproto.org/capnproto-c++-0.9.1-rc1.tar.gz

Can someone verify it works correctly with XCode 11?

**Comment by judaew** [comment]
LGTM, CI builds correctly.
