### PR TITLE
Use kj::max instead of std::max in kj/timer.c++ (was: Include <algorithm> in kj/timer.c++ to satisfy clang-20)

### PR DESCRIPTION
**Pull request by lewinb-corp**
I noticed that compiling `libkj` fails with clang-20.1.5 for me:

```
/home/lewinb/.conan2/p/b/capnp25c9fdddbfd6b/b/src/c++/src/kj/timer.c++:118:10: error: no member named 'max' in namespace 'std'; did you mean simply 'max'?
  118 |   time = std::max(time, newTime);
      |          ^~~~~~~~
      |          max
```

This PR fixes the error by including `<algorithm>` for `std::max()` on `master`.

### CODE REVIEW

**Comment by kentonv** [comment]
This may have broken with 6cf179bd799b66cb56185dc834b54b3355163c08 -- before that the line was only compiled on Mac.

The right answer here, though, is probably to use `kj::max` instead of `std::max`. I'm a little surprised to see this using `std::max`, actually. (`kj::max` is generally better as it can deal with the argument types not being the same, not that that matters here.)

**Comment by lewinb-corp** [comment]
Sounds good, I've updated the commit accordingly.

**Comment by kentonv** [comment]
Oh man, I just pushed a release yesterday, forgot this was still pending. Guess I'll have to push another one.

Oh well, thanks for the fix in any case!
