### ISSUE TITLE
capnproto test failures on Linux aarch64

### ISSUE THREAD

**Issue by martin-g** [capnproto/capnproto#1982]
The conda-forge Arch migration [PR](https://github.com/conda-forge/capnproto-feedstock/pull/43) failed because of the following tests:
- [ FAIL ] kj/async-io-test.c++:3241: OS handle pumpTo write buffer is full before pump (3403 μs)
- [ FAIL ] kj/async-io-test.c++:3275: OS handle pumpTo write buffer is full before pump -- and pump ends early (3324 μs)
- [ FAIL ] kj/async-io-test.c++:3304: OS handle pumpTo write buffer is full before pump -- and pump hits limit early (3299 μs)
- [ FAIL ] kj/async-io-test.c++:3332: OS handle pumpTo write buffer is full before pump -- and a lot of data is pumped (3353 μs)
- [ FAIL ] kj/compat/tls-test.c++:650: TLS full duplex (115185 μs)

I tried to build capnproto on my Linux Aarch64 VM but with GCC-10/CLANG-12 I get these errors:
```
./src/kj/async-inl.h:2081:8: error: explicit specialization of undeclared template struct 'coroutine_traits'
struct coroutine_traits<kj::Promise<T>, Args...> {
       ^               ~~~~~~~~~~~~~~~~~~~~~~~~~
./src/kj/async-inl.h:2121:26: error: no template named 'coroutine_handle' in namespace 'KJ_COROUTINE_STD_NAMESPACE'
  CoroutineBase(stdcoro::coroutine_handle<> coroutine, ExceptionOrValue& resultRef,
                ~~~~~~~~~^
./src/kj/async-inl.h:2168:12: error: no template named 'coroutine_handle' in namespace 'KJ_COROUTINE_STD_NAMESPACE'
  stdcoro::coroutine_handle<> coroutine;
  ~~~~~~~~~^
./src/kj/async-inl.h:2127:44: error: no member named 'suspend_never' in namespace 'KJ_COROUTINE_STD_NAMESPACE'
  auto initial_suspend() { return stdcoro::suspend_never(); }
                                  ~~~~~~~~~^
```

And with GCC-12 the compilation fails due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102051

The build script could be found at https://github.com/conda-forge/capnproto-feedstock/blob/412fdd117b124073b2c66cff5ea16cb272ba7f24/recipe/build.sh

Any hints how to fix these issues ?
Thanks!

**Comment by kentonv** [comment]
We regularly build and run these tests on linux-aarch64 for Cloudflare Workers, and I haven't seen these tests fail. It's hard for me to say anything about what might be going wrong with them without seeing the test logs. (You have provided a list of failing tests, but not the associated error messages...)

Please make sure you are building from the `master` branch and not the `v2` branch. The `v2` branch is the "default" branch on github because that's where development is happening, but the `master` branch is the stable release branch which is what you should be using here. I believe this should fix the compiler errors you noticed, which are specific to the `v2` branch.

**Comment by martin-g** [comment]
Hi @kentonv !

The full logs from the CI build could be seen at https://app.travis-ci.com/github/conda-forge/capnproto-feedstock/jobs/618753138

I will try to build `master` on my dev machine!

**Comment by martin-g** [comment]
`master` branch builds fine on my dev machine! Same for `v1.0.2` tag!
Please feel free to close the issue if the TravisCI logs are not actionable!
Thank you!
