### ISSUE TITLE
Workaround for clang svn trunk

### ISSUE THREAD

**Issue by 191919** [capnproto/capnproto#28]
clang trunk (188673 I tried) failed to compile capnproto and gave the following error:

```
./src/kj/parse/../tuple.h:281:10: error: call to 'expandAndApplyWithIndexes' is ambiguous
  return expandAndApplyWithIndexes(MakeIndexes<sizeof...(FirstTypes)>(),
```

I made a lame workaround to make it compilable:

```
diff --git a/c++/src/kj/tuple.h b/c++/src/kj/tuple.h
index f7427cc..54d4750 100644
--- a/c++/src/kj/tuple.h
+++ b/c++/src/kj/tuple.h
@@ -265,10 +265,12 @@ inline auto expandAndApply(Func&& func, First&& first, Rest&&... rest)
       kj::fwd<Rest>(rest)...);
 }

+/*!!!
 template <typename Func, typename... FirstTypes, typename... Rest, size_t... indexes>
 inline auto expandAndApplyWithIndexes(
     Indexes<indexes...>, Func&& func, Tuple<FirstTypes...>&& first, Rest&&... rest)
     -> ExpandAndApplyResult<Func, FirstTypes&&..., Rest...>;
+!!!*/

 template <typename Func, typename... FirstTypes, typename... Rest, size_t... indexes>
 inline auto expandAndApplyWithIndexes(
```

This also compiles with clang-3.2 and gcc-4.8.1.
