### ISSUE TITLE
Compile error using capnproto ("expected unqualified-id before numeric constant")

### ISSUE THREAD

**Issue by z3ntu** [capnproto/capnproto#1393]
Hi, since the upgrade of capnproto from 0.8.0 to 0.9.1 a piece of software depending on capnproto doesn't compile anymore with such an error:
```
In file included from /usr/include/X11/Xlib.h:44,
                 from test.cpp:1:
/usr/include/kj/one-of.h:54:15: error: expected unqualified-id before numeric constant
   54 |   typedef int Success;
      |               ^~~~~~~
/usr/include/kj/one-of.h:156:89: error: expected identifier before numeric constant
  156 |   template <typename... OtherVariants, typename = typename HasAll<1, OtherVariants...>::Success>
      |                                                                                         ^~~~~~~
/usr/include/kj/one-of.h:156:89: error: expected ‘>’ before numeric constant
/usr/include/kj/one-of.h:158:89: error: expected identifier before numeric constant
  158 |   template <typename... OtherVariants, typename = typename HasAll<1, OtherVariants...>::Success>
      |                                                                                         ^~~~~~~
/usr/include/kj/one-of.h:158:89: error: expected ‘>’ before numeric constant
/usr/include/kj/one-of.h:160:89: error: expected identifier before numeric constant
  160 |   template <typename... OtherVariants, typename = typename HasAll<1, OtherVariants...>::Success>
      |                                                                                         ^~~~~~~
/usr/include/kj/one-of.h:160:89: error: expected ‘>’ before numeric constant
/usr/include/kj/one-of.h:164:66: error: expected identifier before numeric constant
  164 |   template <typename T, typename = typename HasAll<0, Decay<T>>::Success>
      |                                                                  ^~~~~~~
/usr/include/kj/one-of.h:164:66: error: expected ‘>’ before numeric constant
```
This is caused by the software including the header `X11/Xlib.h` as well as capnproto headers (incl. `kj/one-of.h`)
Capnproto contains this: `typedef int Success;` while `X11/X.h` (included by `Xlib.h`) contains this: `#define Success		   0	/* everything's okay */` and the compiler really doesn't like `Success` being defined differently and twice.

See this very simple test reproducer:
```c
#include <X11/Xlib.h>
#include <kj/one-of.h>
int main() {}
```

**Comment by z3ntu** [comment]
Huh, I just tried swapping the order of the includes and that makes gcc happy for some reason
```c
#include <kj/one-of.h>
#include <X11/Xlib.h>
int main() {}
```

This also seems to work outside of this proof-of-concept in the actual software I'm building, I'll let this be the workaround for now.

**Comment by AlanGriffiths** [comment]
I'd say the problem is with the Xlib code that defines the MixedCase macro, not with capnproto. There's a convention that macros are UPPERCASE for a good reason.

**Comment by kentonv** [comment]
Yeah, sorry, this is mostly a problem with Xlib. Cap'n Proto can't be expected to anticipate and work around every `#define` in every C library out there.

You can use a sequence like the following to convert `Success` from a macro into a constant:

```
#ifdef Success
constexpr auto Success_ = Success;
#undef Success;
constexpr auto Success = Success_;
#endif
```

I'd be willing to accept a PR adding those lines to `one-of.h` but can't guarantee there won't be other problems like this in the future.

**Comment by z3ntu** [comment]
Okay I understand. Given I have found a workaround (order the includes differently) I can make it work. Thanks!
