### ISSUE TITLE
Compilation failure on NetBSD 10.0 with GCC 14.2

### ISSUE THREAD

**Issue by hebasto** [capnproto/capnproto#2201]
The master branch @ 7d39134b280182bd0854339eacb521bb6fd9fb50 fails to compile on NetBSD 10.0 when using GCC 14.2:
```
$ cd c++
$ autoreconf -i
$ ./configure CXX=/usr/pkg/gcc14/bin/g++
$ make
...
libtool: compile:  /usr/pkg/gcc14/bin/g++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -pthread -O2 -DNDEBUG -pthread -DKJ_HAS_ZLIB -DKJ_HAS_OPENSSL -DKJ_USE_FIBERS -MT src/kj/async-io-unix.lo -MD -MP -MF src/kj/.deps/async-io-unix.Tpo -c src/kj/async-io-unix.c++  -fPIC -DPIC -o src/kj/.libs/async-io-unix.o
In file included from ./src/kj/memory.h:24,
                 from ./src/kj/exception.h:24,
                 from src/kj/async-prelude.h:27,
                 from src/kj/async.h:24,
                 from src/kj/async-io.h:24,
                 from src/kj/async-io-unix.c++:35:
src/kj/async-io-unix.c++: In lambda function:
src/kj/async-io-unix.c++:1243:24: error: 'AI_V4MAPPED' was not declared in this scope
 1243 |       hints.ai_flags = AI_V4MAPPED | AI_ADDRCONFIG;
      |                        ^~~~~~~~~~~
./src/kj/common.h:1322:67: note: in definition of macro 'KJ_IF_MAYBE'
 1322 | #define KJ_IF_MAYBE(name, exp) if (auto name = ::kj::_::readMaybe(exp))
      |                                                                   ^~~
*** [src/kj/async-io-unix.lo] Error code 1

make[1]: stopped in /home/hebasto/dev/capnproto/c++
1 error

make[1]: stopped in /home/hebasto/dev/capnproto/c++

make: stopped in /home/hebasto/dev/capnproto/c++
```
